In [ ]:
import pandas as pd

In [16]:
df_path = '/content/drive/MyDrive/Colab Notebooks/Third semester/Sentiment - Practical Part/Data/rusentitweet_test_cleaned.csv'

In [17]:
df = pd.read_csv(df_path)
df.head()

,text,label,id
0,я считаю это мем года https://t.co/xoVKj5y8Mj,positive,1218052288964632576
1,ян русский на сотку все запятые где надо🤙🏻👍🏻👍🏻...,positive,1212859589592539136
2,@daria_karapet * терияки бойз начинает играть*,neutral,1321540138334302209
3,(пушка на Караульной горе больше не стреляет Б...,negative,1342696727808274432
4,@Iori_loves_U Как мило /смутилась/ спасибо 🥰🌸,positive,1317052132382679041

In [20]:
df_50 = df['text'][:50]

In [21]:
df_50

0         я считаю это мем года https://t.co/xoVKj5y8Mj
1     ян русский на сотку все запятые где надо🤙🏻👍🏻👍🏻...
2        @daria_karapet * терияки бойз начинает играть*
3     (пушка на Караульной горе больше не стреляет Б...
4         @Iori_loves_U Как мило /смутилась/ спасибо 🥰🌸
5     @dinosaurgrgrgr ПО ДЖАКУРАМАМ ЭТО ПАБЛИК НАРОЧ...
6           мне больно дышать..я как бабка 80 лет ужас🚬
7     @YourChoice602 @crystal_ikon Люблю вас, too 💜 ...
8      @Oppocum09 У нас в столовке лудшая греча с мясом
9                              @94tommo91 какого цвета?
10    Ради теста воткнул в планшет SDR-приемник\r\n\...
11                      @lilydavay @bikymora Так лучше)
12                             @ineedanescap Волнуемся🤗
13                   @hongjoongscoat НЕТ Я ВОУД В ТАНЦЕ
14                                         Вот и чудно.
15    @Oleg_Ilchenko Как можно было выходить за муж ...
16    @CulturalBaby ого они реально упомянули эспу\r...
17                                 @OvvCheck у меня. ⚰️
18                   @boglaid ОНА ВЕРНЕЕЕЕТСЯЯЯЯЯЯЯЯЯЯЯ
19    По словам разработчиков, эффективность российс...
20               @wCZLmLwTtbDokr5 Это какой-то пипец)))
21                                   @sumin174 Согласна
22                       @flufairii как же секси скажии
23    @niemalsnoch @veritas_z ну кто ты и кто залина...
24    от красных носков неприятно несёт гетеронормат...
25    НЕ НУ ВЫ ВИДЕЛИ ЧЕ ТВОРЯТ???\r\n\r\n#NCT127 #P...
26    Я ещё только на 12-ой минуте выпуска и я уже с...
27    Тот человек, у которого истинные друзья не ост...
28    да полюбас лирику поменяли всегда же меняют об...
29    Ненавижу детей с колонками, вы, суки, мешаете ...
30                                               АХУЕТЬ
31                         @pineorangene оль, это бан 🥴
32         @meduzaproject Пусть земля ему будет Крымом!
33                 @zhongguodangren Почему культуристы?
34    Почему умирают реально достойные люди, а я жив...
35          @Umfcsamregion ну вот и дождались. спасибо.
36       нахуй я интересуюсь если ты игноришь лол ладно
37    @Nitograve @VayMarin Я не понимаю о чем вы, а ...
38    @ksuharik я тоже не знала про его альбом, случ...
39                   @GoretcNew и несёт её очень часто.
40    @TAMRUS15 Это же сексуально аппетитная попка @...
41    @douknowwhou это буквально ты мучача https://t...
42                              💢Кто и что вас бесит?💢😾
43                                 @senyahuduakov давай
44    сначала арт для фавочки\r\nпотом арт с Сонхва\...
45    ТВОЮ МАТЬ СЁДЗИ ЧЕ ТЫ ТВОРИШЬ\r\nАААААааАаАаАа...
46    я в 5 классе                      я на 3 курсе...
47    @vova_kovynev @mexelmexel @quintocolumno1 морг...
48    @traktor_bang Не читаю реплаи и цитирование тв...
49    самый сильный аргумент educate yourself 👍 испо...
Name: text, dtype: object

In [22]:
from google.colab import files

In [23]:
df_50.to_excel('df_50.xlsx')

In [25]:
files.download('df_50.xlsx')

In [26]:
df_50_label = df['label'][:50]

In [27]:
df_50_label.to_excel('df_50_label.xlsx')

In [28]:
files.download('df_50_label.xlsx')