# Импорт

In [2]:
import pandas as pd

# Оценка структуры

In [4]:
test_path = '/content/drive/MyDrive/Colab Notebooks/Third semester/Sentiment - Practical Part/Data/rusentitweet_test.csv'

In [5]:
df = pd.read_csv(test_path)
df.head()

,text,label,id
0,все мы помним мой ахуй https://t.co/3Kr7yzeYLC,skip,1318021368932421633
1,я считаю это мем года https://t.co/xoVKj5y8Mj,positive,1218052288964632576
2,ян русский на сотку все запятые где надо🤙🏻👍🏻👍🏻...,positive,1212859589592539136
3,бэк дор соти https://t.co/bYCWz4h4Sk,skip,1306944400824709120
4,@daria_karapet * терияки бойз начинает играть*,neutral,1321540138334302209

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2679 entries, 0 to 2678
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    2679 non-null   object
 1   label   2679 non-null   object
 2   id      2679 non-null   int64
dtypes: int64(1), object(2)
memory usage: 62.9+ KB

In [11]:
df.columns

Index(['text', 'label', 'id'], dtype='object')

In [12]:
df.groupby('label').count()

          text    id
label
negative   660   660
neutral   1068  1068
positive   483   483
skip       369   369
speech      99    99

# Удаляем неподходящие строки

In [14]:
idxs_to_drop = df[df['label'].isin(['skip', 'speech'])].index
idxs_to_drop

Index([   0,    3,    8,   23,   28,   29,   30,   32,   33,   35,
       ...
       2634, 2635, 2639, 2643, 2657, 2659, 2663, 2668, 2669, 2675],
      dtype='int64', length=468)

In [15]:
df.shape

(2679, 3)

In [16]:
df.drop(idxs_to_drop, inplace=True)

In [17]:
df.shape

(2211, 3)

In [18]:
df.head()

,text,label,id
1,я считаю это мем года https://t.co/xoVKj5y8Mj,positive,1218052288964632576
2,ян русский на сотку все запятые где надо🤙🏻👍🏻👍🏻...,positive,1212859589592539136
4,@daria_karapet * терияки бойз начинает играть*,neutral,1321540138334302209
5,(пушка на Караульной горе больше не стреляет Б...,negative,1342696727808274432
6,@Iori_loves_U Как мило /смутилась/ спасибо 🥰🌸,positive,1317052132382679041

# Скачиваем результат

In [19]:
from google.colab import files

In [20]:
df.to_csv('rusentitweet_test_cleaned.csv', index=False)

In [21]:
files.download('rusentitweet_test_cleaned.csv')